version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - kafka
      - redis
    volumes:
      - ./analytics-engine:/app/analytics-engine
      - ./leaderboard-service:/app/leaderboard-service
      - ./player-tracker:/app/player-tracker
    working_dir: /app
    command: >
      bash -c "
      python3 leaderboard-service/app.py &
      python3 analytics-engine/consumer.py &
      python3 player-tracker/tracker.py
      "
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./leaderboard-frontend
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
